### ISSUE TITLE
Add Equinor SCM badge to all module repositories

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#113]
Add the following badge to the top of the README for each module repo:

```markdown
[![SCM Compliance](https://scm-compliance-api.radix.equinor.com/repos/equinor/terraform-azurerm-<module>/badge)](https://scm-compliance-api.radix.equinor.com/repos/equinor/terraform-azurerm-<module>/badge)
```

> [!IMPORTANT]
>
> The badge is unique for each repo! Remember to not simply copy paste the above code for each repo.

This badge will be green if the module repo is compliant with Equinor source control management (SCM) policies, or red if not.

Since this badge is generated by an app which runs daily, it can take up to 24 hours before the badge is working as expected.

## Tasks

- [x] Add badge to this repo
- [x] Add badge to [web-app](https://github.com/equinor/terraform-azurerm-web-app) module repo
- [x] Add badge to [storage](https://github.com/equinor/terraform-azurerm-storage) module repo
- [x] Add badge to [log-analytics](https://github.com/equinor/terraform-azurerm-log-analytics) module repo
- [x] Add badge to [network](https://github.com/equinor/terraform-azurerm-network) module repo
- [x] Add badge to [databricks](https://github.com/equinor/terraform-azurerm-databricks) module repo
- [x] Add badge to [synapse](https://github.com/equinor/terraform-azurerm-synapse) module repo
- [x] Add badge to [app-insights](https://github.com/equinor/terraform-azurerm-app-insights) module repo
- [x] Add badge to [grafana](https://github.com/equinor/terraform-azurerm-grafana) module repo
- [x] Add badge to [vm](https://github.com/equinor/terraform-azurerm-vm) module repo
- [x] Add badge to [app-service](https://github.com/equinor/terraform-azurerm-app-service) module repo
- [x] Add badge to [container-app](https://github.com/equinor/terraform-azurerm-container-app) module repo
- [x] Add badge to [nat](https://github.com/equinor/terraform-azurerm-nat) module repo
- [x] Add badge to [acr](https://github.com/equinor/terraform-azurerm-acr) module repo
- [x] Add badge to [public-ip](https://github.com/equinor/terraform-azurerm-public-ip) module repo
- [x] Add badge to [automation](https://github.com/equinor/terraform-azurerm-automation) module repo
- [x] Add badge to [key-vault](https://github.com/equinor/terraform-azurerm-key-vault) module repo
- [x] Add badge to [event-grid](https://github.com/equinor/terraform-azurerm-event-grid) module repo
- [x] Add badge to [sql](https://github.com/equinor/terraform-azurerm-sql) module repo
- [x] Add badge to [app-config](https://github.com/equinor/terraform-azurerm-app-config) module repo
- [x] Add badge to [identity](https://github.com/equinor/terraform-azurerm-identity) module repo
- [x] Add badge to [service-bus](https://github.com/equinor/terraform-azurerm-service-bus) module repo
- [x] Add badge to [function-app](https://github.com/equinor/terraform-azurerm-function-app) module repo
- [x] Add badge to [postgres](https://github.com/equinor/terraform-azurerm-postgres) module repo
- [x] Add badge to [template](https://github.com/equinor/terraform-module-template) repo
- [x] Verify that all badges are working as expected

**Comment by kov117** [comment]
I can confirm that all these modules repositories now have equinor scm badge, and that it is working as it should, i will let @hknutsen confirm this and close this issue when he does so 👍🏼

**Comment by hknutsen** [comment]
@kov117 Looks good 🙌

**Comment by kov117** [comment]
then with that i will close this issue as complete 💯
