### ISSUE TITLE
chore: set diagnostic setting enabled log categories

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#19]
Update all modules to allow setting diagnostic setting enabled log categories

- [x] equinor/terraform-azurerm-acr#40
- [x] App Config (Already updated.) Ref. [discussion](https://github.com/equinor/terraform-azurerm-app-config/issues/7)
- [x] App Insights -> Omitting diagnostic setting from app-insights module, ref. [Workspace-based App Insights vs. Diagnostic settings](https://learn.microsoft.com/en-us/answers/questions/775202/workspace-based-app-insights-vs-diagnostic-setting)
- [x] equinor/terraform-azurerm-app-service#5
- [x] Automation (Already updated.)
- [x] equinor/terraform-azurerm-container#23
- [x] equinor/terraform-azurerm-databricks#18
- [x] equinor/terraform-azurerm-event-grid#6
- [x] equinor/terraform-azurerm-function-app#6
- [x] Grafana (Already updated.
- [x] Identity (Diagnostic settings are not supported for the resource created by this module)
- [x] equinor/terraform-azurerm-key-vault#53
- [x] equinor/terraform-azurerm-log-analytics#22
- [x] equinor/terraform-azurerm-network#20
- [x] Postgres (Already updated.)
- [x] https://github.com/equinor/terraform-azurerm-sql/issues/61
- [x] equinor/terraform-azurerm-storage#138
- [x] equinor/terraform-azurerm-web-app#87

**Comment by helenakallekleiv** [comment]
All modules have been updated, closing this issue.
