### ISSUE TITLE
Enforce network rules by default

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-baseline#47]
All modules should deny all traffic by default for all relevant resources, unless it's a service that is usually exposed to the internet (e.g. a Web App).

Should also add this as a best practice in this repo.

## Tasks

- [ ] [equinor/app-config/azurerm](https://registry.terraform.io/modules/equinor/app-config/azurerm/latest)
- [ ] [equinor/app/azuread](https://registry.terraform.io/modules/equinor/app/azuread/latest)
- [ ] [equinor/mysql/azurerm](https://registry.terraform.io/modules/equinor/mysql/azurerm/latest)
- [ ] [equinor/acr/azurerm](https://registry.terraform.io/modules/equinor/acr/azurerm/latest)
- [x] equinor/terraform-azurerm-storage#158
- [x] equinor/terraform-azurerm-key-vault#57
- [x] https://github.com/equinor/terraform-azurerm-web-app/pull/200
- [ ] [equinor/vm/azurerm](https://registry.terraform.io/modules/equinor/vm/azurerm/latest)
- [x] https://github.com/equinor/terraform-azurerm-service-bus/pull/58
- [ ] [equinor/sql/azurerm](https://registry.terraform.io/modules/equinor/sql/azurerm/latest)
- [ ] [equinor/log-analytics/azurerm](https://registry.terraform.io/modules/equinor/log-analytics/azurerm/latest)
- [ ] [equinor/nat/azurerm](https://registry.terraform.io/modules/equinor/nat/azurerm/latest)
- [ ] [equinor/grafana/azurerm](https://registry.terraform.io/modules/equinor/grafana/azurerm/latest)
- [ ] [equinor/network/azurerm](https://registry.terraform.io/modules/equinor/network/azurerm/latest)
- [x] [equinor/app-service/azurerm](https://registry.terraform.io/modules/equinor/app-service/azurerm/latest) (N/A)
- [ ] [equinor/databricks/azurerm](https://registry.terraform.io/modules/equinor/databricks/azurerm/latest)
- [ ] [equinor/app-insights/azurerm](https://registry.terraform.io/modules/equinor/app-insights/azurerm/latest)
- [ ] [equinor/automation/azurerm](https://registry.terraform.io/modules/equinor/automation/azurerm/latest)
- [x] https://github.com/equinor/terraform-azurerm-function-app/pull/69
- [ ] [equinor/postgres/azurerm](https://registry.terraform.io/modules/equinor/postgres/azurerm/latest)
- [ ] [equinor/identity/azurerm](https://registry.terraform.io/modules/equinor/identity/azurerm/latest)
- [ ] [equinor/event-grid/azurerm](https://registry.terraform.io/modules/equinor/event-grid/azurerm/latest)
- [ ] [equinor/public-ip/azurerm](https://registry.terraform.io/modules/equinor/public-ip/azurerm/latest)
- [ ] [equinor/container-app/azurerm](https://registry.terraform.io/modules/equinor/container-app/azurerm/latest)
- [ ] [equinor/synapse/azurerm](https://registry.terraform.io/modules/equinor/synapse/azurerm/latest)

**Comment by hknutsen** [comment]
Investigate if any other modules require similar updates.

**Comment by helenakallekleiv** [comment]
In addition to Storage and Key Vault, a similar update to the Service Bus module may be required (based on policy).

**Comment by musifalsk** [comment]
- [ ] terraform-azurerm-postgres - public_network_access_enabled
```hcl
variable "public_network_access_enabled" {
  description = "Should public network access be enabled for this PostgreSQL server?"
  type        = bool
  default     = true
}
```
- [ ] terraform-azurerm-sql - firewall_rules

```hcl
variable "firewall_rules" {
  description = "A map of firewall rules to be configured for this SQL server."

  type = map(object({
    name             = string
    start_ip_address = string
    end_ip_address   = string
  }))

  default = {
    "azure" = {
      name             = "AllowAllWindowsAzureIps"
      start_ip_address = "0.0.0.0"
      end_ip_address   = "0.0.0.0"
    }
  }
}
```

**Comment by musifalsk** [comment]
- [] terraform-azurerm-function-app - missing variable for ip_restriction. Should this be implemented as an option?

**Comment by musifalsk** [comment]
- [ ] terraform-azurerm-service-bus
![image](https://github.com/user-attachments/assets/5eb8a06c-5009-403b-a229-2f93584bedd1)
This is the only configuration i could find for this, and it looks like its related to outbound access. I cannot find this setting or other restrictive network setting on the namespace in the azure portal.
**NB! The Service Bus module is missing essential resources to become complete:**
 - azurerm_servicebus_queue
 - azurerm_servicebus_namespace_authorization_rule
 - azurerm_servicebus_queue_authorization_rule

**Comment by musifalsk** [comment]
- [ ] terraform-azurerm-grafana
public_network_access_enabled is hardcoded in this module. Should this be changed to a variable with a default value of disabled?
```hcl
public_network_access_enabled     = true
```

**Comment by musifalsk** [comment]
remains to clarify what to do and not

**Comment by hknutsen** [comment]
Regarding public network access:

We usually leave it enabled, but deny all traffic by default. For example, look at the wording in the features section in the Key Vault module README:

![Image](https://github.com/user-attachments/assets/b6f226a8-dd5d-4933-9708-34fc87491eb4)

**Comment by helenakallekleiv** [comment]
> * [ ]  terraform-azurerm-service-bus
>       ![image](https://private-user-images.githubusercontent.com/117847311/355845962-5eb8a06c-5009-403b-a229-2f93584bedd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjk1MjcsIm5iZiI6MTcyNDIyOTIyNywicGF0aCI6Ii8xMTc4NDczMTEvMzU1ODQ1OTYyLTVlYjhhMDZjLTUwMDktNDAzYi1hMjI5LTJmOTM1ODRiZWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwODMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODEyYjYyMWE0ZTU5ZTc2ZjMzY2U5MTk5YmExZThjM2ZkZWQzYjAzOThjZjZiMWQ2MmFjM2MxMmY0MWEzNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8XynV8NpBot8G3DVzhFiZo9YmhBr922bwUipA7MP6Ew)
>       This is the only configuration i could find for this, not sure if this relates to inbound or outbound access. I cannot find this setting or other restrictive network setting on the namespace in the azure portal.


Could be useful: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace_network_rule_set

**Comment by helenakallekleiv** [comment]
Moving back to "In progress". Se if we can create new subissues from this after some investigation.

**Comment by hknutsen** [comment]
> > * [ ]   terraform-azurerm-service-bus
> >   ![image](https://private-user-images.githubusercontent.com/117847311/355845962-5eb8a06c-5009-403b-a229-2f93584bedd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjk1MjcsIm5iZiI6MTcyNDIyOTIyNywicGF0aCI6Ii8xMTc4NDczMTEvMzU1ODQ1OTYyLTVlYjhhMDZjLTUwMDktNDAzYi1hMjI5LTJmOTM1ODRiZWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwODMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODEyYjYyMWE0ZTU5ZTc2ZjMzY2U5MTk5YmExZThjM2ZkZWQzYjAzOThjZjZiMWQ2MmFjM2MxMmY0MWEzNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8XynV8NpBot8G3DVzhFiZo9YmhBr922bwUipA7MP6Ew)
> >   This is the only configuration i could find for this, not sure if this relates to inbound or outbound access. I cannot find this setting or other restrictive network setting on the namespace in the azure portal.
> 
> Could be useful: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace_network_rule_set

Removed in Azure provider v4.

**Comment by hknutsen** [comment]
Could add overview of **all** module repos in issue description to keep track of which modules we have checked and not.
